server:
  tomcat:
    maxThreads: 500
    uri-encoding: UTF-8
    maxConnections: 2000
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  resources:
    static-locations:
      - file:public/
flowable:
  #enable-history-cleaning: true
  #history-cleaning-cycle: 0/1 * * * * ?
  #history-cleaning-after: 365
  #history-cleaning-batchSize: 100
  idm:
    enabled: false
  label-font-name: 宋体
  activity-font-name: 宋体
  annotation-font-name: 宋体
  #database-schema-update: false
  async-executor-activate: false
# 文件上传配置:local 本地存储、aliOss 阿里云对象存储
lego:
  file:
    config: local
    local:
      uploadPath: /upload
    oss:
      endpoint:
      accessKeyId:
      accessKeySecret:
      publicUrl:
      bucketName:
# sa-token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: ${lego.token-name:lego-admin}
  # token有效期，单位s 默认30天, -1代表永不过期 
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  active-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录) 
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token) 
  is-share: false
  # token风格
  token-style: random-64
  # 是否输出操作日志 
  is-log: false
  is-print: false
# xxl-job定时任务
xxl:
  job:
    accessToken: ${lego.job.accessToken:lego-admin}
    executor:
      appname: ${spring.application.name:xxl-job-executor-sample}
    i18n: zh_CN
    # job-admin
    triggerpool:
      fast:
        max: 200
      slow:
        max: 100
    logretentiondays: 30
feign:
  client:
    config:
      default:
        connect-timeout: 60000
        read-timeout: 60000
  sentinel:
    enabled: true
  httpclient:
    enabled: false
  okhttp:
    enabled: true