spring:
  datasource:
    dynamic:
      enabled: true
      primary: system
      strict: false
      druid:
        initial-size: 5
        min-idle: 5
        max-active: 15
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        filters: stat,wall
        connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        use-global-datasource-stat: true
      datasource:
        system:
          name: 默认
          url: ${jdbc.url}
          username: ${jdbc.username}
          password: ${jdbc.password}
          driver-class-name: ${jdbc.classname}
        crm:
          name: crm
          url: ${jdbc.crm.url}
          username: ${jdbc.crm.username}
          password: ${jdbc.crm.password}
          driver-class-name: ${jdbc.crm.classname}
