spring:
  cloud:
    gateway:
      routes:
        - id: system
          uri: lb://system
          predicates:
            - Path=/back-end/sys-*/**,/back-end/flowable-*/**,/back-end/sharding-*/**
          filters:
            - StripPrefix=1
        - id: crm
          uri: lb://crm
          predicates:
            - Path=/back-end/crm-*/**
          filters:
            - StripPrefix=1
        - id: report
          uri: lb://report
          predicates:
            - Path=/back-end/report-*/**
          filters:
            - StripPrefix=1
        - id: doc
          uri: lb://doc
          predicates:
            - Path=/back-end/doc-*/**
          filters:
            - StripPrefix=1
        - id: job
          uri: lb://job
          predicates:
            - Path=/back-end/job-*/**
          filters:
            - StripPrefix=1
lego:
  open-request-log: true
  # 防止XSS攻击
  xss:
    enabled: false
    excludeUrls:
      - /back-end/sys-notice-template/**
      - /back-end/report-definition/**
      - /back-end/flowable-model/**
  # 不校验白名单
  ignore:
    urls:
      - /back-end/sys-index/login
      - /back-end/sys-index/logout
      - /back-end/sys-index/captchaImage
      - /back-end/sys-index/init