spring:
  cloud:
    gateway:
      routes:
        - id: system
          uri: lb://system
          predicates:
            - Path=/back-end/sys-*/**,/back-end/flowable-*/**,/back-end/sharding-*/**
          filters:
            - StripPrefix=1
        - id: crm
          uri: lb://crm
          predicates:
            - Path=/back-end/crm-*/**
          filters:
            - StripPrefix=1
        - id: report
          uri: lb://report
          predicates:
            - Path=/back-end/report-*/**
          filters:
            - StripPrefix=1
        - id: doc
          uri: lb://doc
          predicates:
            - Path=/back-end/doc-*/**
          filters:
            - StripPrefix=1
        - id: job
          uri: lb://job
          predicates:
            - Path=/back-end/job-*/**
          filters:
            - StripPrefix=1
lego:
  open-request-log: true
  # 防止XSS攻击
  xss:
    enabled: false
    excludeUrls:
      - /back-end/sys-notice-template/**
      - /back-end/report-definition/**
      - /back-end/flowable-model/**
  # 不校验白名单
  ignore:
    urls:
      - /back-end/sys-index/login
      - /back-end/sys-index/logout
      - /back-end/sys-index/captchaImage
# sa-token配置
sa-token:
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: random-64
  # 是否输出操作日志
  is-log: false
  is-print: false